export const REDUCER_KEY = 'reduxHookForm';

export const BLUR = `${REDUCER_KEY}/BLUR`;
export const CHANGE = `${REDUCER_KEY}/CHANGE`;
export const DESTROY_FORM = `${REDUCER_KEY}/DESTROY_FORM`;
export const FOCUS = `${REDUCER_KEY}/FOCUS`;
export const INIT_FIELD = `${REDUCER_KEY}/INIT_FIELD`;
export const MOUNT_FORM = `${REDUCER_KEY}/MOUNT_FORM`;
export const SET_PENDING = `${REDUCER_KEY}/SET_PENDING`;
export const SET_PENDING_FIELD = `${REDUCER_KEY}/SET_PENDING_FIELD`;
export const SET_TOUCHED_FIELD = `${REDUCER_KEY}/SET_TOUCHED`;
export const SUBMIT = `${REDUCER_KEY}/SUBMIT`;
export const SUBMIT_ERROR = `${REDUCER_KEY}/SUBMIT_ERROR`;
export const SUBMIT_SUCCESS = `${REDUCER_KEY}/SUBMIT_SUCCESS`;
export const UPDATE_ASYNC_ERRORS = `${REDUCER_KEY}/UPDATE_ASYNC_ERRORS`;
export const UPDATE_FORM_VALIDATOR = `${REDUCER_KEY}/UPDATE_FORM_VALIDATOR`;
export const UPDATE_SYNC_ERRORS = `${REDUCER_KEY}/UPDATE_SYNC_ERRORS`;
