export enum E2EAttribute {
  componentBlock = 'component-block',
  componentBlockNode = 'component-block-node',
  componentConnector = 'component-connector',
  componentConnectorPath = 'component-line-path',
  componentsPanelBlock = 'components-panel-block',
  editBlockCoordinatesInput = 'edit-block-coodinates-input',
  editConditionBlockInputRadio = 'edit-condition-block-input-radio',
  editConditionBlockInputText = 'edit-condition-block-input-text',
  editConditionBlockSelect = 'edit-condition-block-select',
  editConnectorInputRadio = 'edit-connector-input-radio',
  navigationLayer = 'navigation-layer',
  text = 'text',
  unselected = 'unselected',
}
